[2021-05-14 14:35:32,029] - [ERROR] - Traceback (most recent call last):
  File "/home/karrylee/PycharmProjects/FIS_Alarm_Combine/test/log_test.py", line 22, in <module>
    a = func()
  File "/home/karrylee/PycharmProjects/FIS_Alarm_Combine/test/log_test.py", line 18, in func
    return 3 / 0
ZeroDivisionError: division by zero

[2021-05-14 14:35:59,529] - [ERROR] - Traceback (most recent call last):
  File "/home/karrylee/PycharmProjects/FIS_Alarm_Combine/test/log_test.py", line 22, in <module>
    a = func()
  File "/home/karrylee/PycharmProjects/FIS_Alarm_Combine/test/log_test.py", line 18, in func
    return 3 / 0
ZeroDivisionError: division by zero

